server:
  port: 8083

spring:
  application:
    name: blog-search-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-offset-reset: earliest
      group-id: blog-search-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  elasticsearch:
    uris: http://127.0.0.1:9200

logging:
  level:
    org.springframework.data.elasticsearch.client: warn
